/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jep.Interpreter;
import jep.SharedInterpreter;

public class App {
    public static void main(String[] args) {
        Interpreter interp = new SharedInterpreter();
        interp.exec("s = 'Hello World'");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("print('AAAAAAAAAAAAAAAAAAAAAAAA')");
        interp.exec("raise ValueError('')");
        
    }
}
